#!/bin/sh

set -e

this=toplevel
indir=debian/tests/coqfiles
outdir=${ADT_ARTIFACTS:-/tmp}/${this}
mkdir -p ${outdir}

cp ${indir}/*.v ${outdir}
cd ${outdir}
for infile in *.v
do
    base=$(basename ${infile})
    coqtop < ${infile} 2> ${base}.err
    if grep -q Error ${base}.err; then exit 1; fi
done
