#!/bin/sh

set -e

CURDIR=`pwd`
ORIG=$1
WORKDIR=`dirname $ORIG`
ORIGFILE=`basename $ORIG`
VERSION=`echo "$ORIGFILE" | sed "s/^coq-\([0-9\.a-z]\+\)\.tar\.gz$/\1/"`

cd $WORKDIR

tar zxf $ORIGFILE

rm -rf coq-$VERSION/doc/common
rm -rf coq-$VERSION/doc/faq
rm -rf coq-$VERSION/doc/RecTutorial
rm -rf coq-$VERSION/doc/refman
rm -rf coq-$VERSION/doc/rt
rm -rf coq-$VERSION/doc/tools
rm -rf coq-$VERSION/doc/tutorial

tar zcf coq_$VERSION+dfsg.orig.tar.gz coq-$VERSION/
rm -rf coq-$VERSION

cd $CURDIR
